template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: matrix_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}                  # Change to your own path
      branches:
        include: ^master$
      gitProvider: {{ .Values.gitProvider }}        # Change to your own GitHub integration name

pipelines:
  - name: matrix_pipeline
    steps:
      - name: step_1
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          nodePools:
            - windowsNP
            - ubuntuNP
            #- macNP
          environmentVariables:             # Sets of environment variables for steplets
            - animal:    dog                # - Set 1
              mineral:   copper
              vegetable: carrot
            - animal:    goat               # - Set 2
              mineral:   iron
              vegetable: broccoli
            - animal:    lizard             # - Set 3
              mineral:   lead            
        execution:
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - echo "Variation animal = ${animal}, mineral = ${mineral}, vegetable = ${vegetable}"            
